image: Ubuntu1804 # образ для сборки
stack: node 16.10.0 # окружение
branches:
  only:
    - main # ветка git
cache: node_modules # кеширование
install:
  - npm install # команда установки зависимостей
build: off
test_script:
  - npm test # скрипт сборки